pipeline {
    agent any

    stages {
        stage('Clippy') {
            agent {
                dockerfile {
                    dir 'automation'
                    reuseNode true
                }
            }
            steps {
                sh 'cargo clippy'
            }
        }
        stage('Rustfmt') {
            agent {
                dockerfile {
                    dir 'automation'
                    reuseNode true
                }
            }
            steps {
                sh 'cargo fmt'
            }
        }
        stage('Check') {
            agent {
                dockerfile {
                    dir 'automation'
                    reuseNode true
                }
            }
            steps {
                sh 'cargo check --target thumbv6m-none-eabi'
                sh 'cargo check --target armv7-unknown-linux-gnueabihf'
                sh 'cargo check --target x86_64-unknown-linux-gnu'
                sh 'cargo check --target thumbv7em-none-eabihf'
            }
        }
    }
}